Include x86intrin.h when compiling with clang-cl instead of mapping MSVC intrinsics
Fixes errors like:

```
[1/177] Building CXX object src\lib\CMakeFiles\fst.dir\mapped-file.cc.obj
FAILED: src/lib/CMakeFiles/fst.dir/mapped-file.cc.obj
C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\Llvm\x64\bin\clang-cl.exe  /nologo -TP  -IC:\Users\dhunt-mateo\git\openfst\src\.\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG   /bigobj /showIncludes /Fosrc\lib\CMakeFiles\fst.dir\mapped-file.cc.obj /Fdsrc\lib\CMakeFiles\fst.dir\fst.pdb -c C:\Users\dhunt-mateo\git\openfst\src\lib\mapped-file.cc
In file included from C:\Users\dhunt-mateo\git\openfst\src\lib\mapped-file.cc:5:
In file included from C:\Users\dhunt-mateo\git\openfst\src\.\include\fst/mapped-file.h:11:
C:\Users\dhunt-mateo\git\openfst\src\.\include\fst/compat.h(59,21): error: functions that differ only in their return type cannot be overloaded
inline unsigned int __builtin_ctzll(std::uint64_t w) {
       ~~~~~~~~~~~~ ^
C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\Llvm\x64\lib\clang\10.0.0\include\ia32intrin.h(90,10): note: previous implicit declaration is here
  return __builtin_ctzll(__A);
         ^
```